### ISSUE TITLE
I-array-properties

### ISSUE THREAD

**Issue by LslyKng** [CodeYourFuture/js-exercises#20]
Can we have the instructions in english please (haha Rares said I should say that). Not clear I needed to copy the below code into terminal to check. 

Arrays, like strings, have a `length` property.

You can check this by starting a node console in your terminal.

```sh
$ node
> var arr = [1, 2, 3];
undefined
> arr
[1, 2, 3]
> arr.length
3
```

**Comment by Omar-Suliman** [comment]
haha ok
